### ISSUE TITLE
Crash: When calendar event that will trigger silence exists

### ISSUE THREAD

**Issue by ruckel** [newhinton/Timed-Silence#17]
- **Description**:  
As soon as I add an event to a calendar that eill trigger silence the app refuses to start.

- **Phone model**:  
Pixel 7
- **OS**:  
Calyx 5.8.0
- **App**:  
version 3.1.1
de.felixnuesse.timedsilence (F-Droid)

**Logcat excerpt**:  
> Logcat turned on when 1 event (at 20:30) was planned to trigger silence. App repeatedly opened.  

<<< log_count = 34 >>>
[07-05 20:23:56.714 16357:16357 E/se.timedsilence]
Not starting debugger since process cannot load the jdwp agent.

[07-05 20:23:56.822 16357:16357 E/MainActivity]
Main: ButtonStartCheck: State: Stopped

[07-05 20:23:56.822 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:23:56.827 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:23:56.833 16357:16357 E/LogHandler]
1720203836833; 2024-07-05T20:23:56.833+0200 [StateGenerator] - instantiate: VolumeCalculator was now instantiated

[07-05 20:23:56.837 16357:16357 E/StateGenerator]
Start-time: 1720203836837

[07-05 20:23:56.866 16357:16357 E/StateGenerator]
Endtime: 1720203836866

[07-05 20:23:56.866 16357:16357 E/StateGenerator]
Diff: 29ms

[07-05 20:23:56.867 16357:16357 E/LogHandler]
1720203836867; 2024-07-05T20:23:56.866+0200 [VolumeHandler] - because applyVolume was called: Loud - Volume changed because of time: week Day

[07-05 20:23:56.878 16357:16357 E/LogHandler]
1720203836878; 2024-07-05T20:23:56.877+0200 [VolumeHandler] - because applyVolume was called: Loud - Volume changed because of time: week Day

[07-05 20:23:56.882 16357:16357 E/MainActivity]
Main: ButtonStartCheck: State: start

[07-05 20:23:56.882 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:23:56.885 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:23:56.914 16357:16357 E/LogHandler]
1720203836914; 2024-07-05T20:23:56.913+0200 [StateGenerator] - instantiate: VolumeCalculator was now instantiated

[07-05 20:23:56.915 16357:16357 E/StateGenerator]
Start-time: 1720203836915

[07-05 20:23:56.925 16357:16357 E/StateGenerator]
Endtime: 1720203836925

[07-05 20:23:56.926 16357:16357 E/StateGenerator]
Diff: 10ms

[07-05 20:24:20.616 16357:16357 E/CalendarDialog]
CalendarDialog: cancel!

[07-05 20:25:34.302 16357:16357 E/MainActivity]
Main: ButtonStartCheck: State: start

[07-05 20:25:34.306 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:25:34.340 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:25:34.408 16357:16357 E/LogHandler]
1720203934408; 2024-07-05T20:25:34.408+0200 [StateGenerator] - instantiate: VolumeCalculator was now instantiated

[07-05 20:25:34.409 16357:16357 E/StateGenerator]
Start-time: 1720203934409

[07-05 20:25:34.424 16357:16357 E/StateGenerator]
Endtime: 1720203934424

[07-05 20:25:34.424 16357:16357 E/StateGenerator]
Diff: 15ms

[07-05 20:25:38.498 16357:16357 E/CalendarDialog]
CalendarDialog: cancel!

[07-05 20:26:01.845 16357:16357 E/MainActivity]
Main: ButtonStartCheck: State: start

[07-05 20:26:01.846 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:26:01.862 16357:16357 E/Companion]
PausedNotification: Show Notification

[07-05 20:26:01.918 16357:16357 E/LogHandler]
1720203961918; 2024-07-05T20:26:01.918+0200 [StateGenerator] - instantiate: VolumeCalculator was now instantiated

[07-05 20:26:01.920 16357:16357 E/StateGenerator]
Start-time: 1720203961920

[07-05 20:26:01.954 16357:16357 E/StateGenerator]
Endtime: 1720203961954

[07-05 20:26:01.954 16357:16357 E/StateGenerator]
Diff: 34ms

[07-05 20:26:01.957 16357:16357 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: de.felixnuesse.timedsilence, PID: 16357
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at de.felixnuesse.timedsilence.volumestate.StateGenerator.padList(StateGenerator.kt:147)
	at de.felixnuesse.timedsilence.volumestate.StateGenerator.states(StateGenerator.kt:113)
	at de.felixnuesse.timedsilence.fragments.graph.GraphFragment.onCreateView(GraphFragment.kt:55)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:540)
	at de.felixnuesse.timedsilence.MainActivity.onResume$lambda$2(MainActivity.kt:187)
	at de.felixnuesse.timedsilence.MainActivity.$r8$lambda$ja3q5jjjz87Et3fEiTzfEQ4Q-8g(Unknown Source:0)
	at de.felixnuesse.timedsilence.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by ruckel** [comment]
Tried the 3.1.2 apk from github, all is well again!
